feat: generate Fortran bindings automatically
JeffersonLab/iguana pull request #250
Opened 2024-07-13 20:36 UTC by c-dilks

2024-07-26 20:22 UTC, rtysonCLAS12 requested changes
Sorry I took so long to review, I forgot about this!
I checked the Action.yaml files, they have the right entries for each action function.

Should the ExampleAlgorithm have an Action.yaml file? This could point to the [action function Filter ](https://github.com/JeffersonLab/iguana/blob/6a7d113c7150b1251a1d0d0fdd4c438033f4165e/src/iguana/algorithms/example/ExampleAlgorithm/Algorithm.cc#L107), I think it would be helpful to refer to when writing algorithms.

2024-07-26 23:37 UTC, c-dilks commented
> Should the ExampleAlgorithm have an Action.yaml file? This could point to the [action function Filter ](https://github.com/JeffersonLab/iguana/blob/6a7d113c7150b1251a1d0d0fdd4c438033f4165e/src/iguana/algorithms/example/ExampleAlgorithm/Algorithm.cc#L107), I think it would be helpful to refer to when writing algorithms.

Yes, but I'm actually considering removing `ExampleAlgorithm` with #141, in favor of choosing three representative algorithms (a filter, a transformer, and a creator) that would serve as good examples, and moving the descriptive comments to those. Then I'll add links to those in the documentation.

2024-07-29 12:50 UTC, rtysonCLAS12 approved these changes
OK sounds good

2024-07-31 16:08 UTC, c-dilks commented on src/iguana/algorithms/clas12/LorentzTransformer/Algorithm.h
> +      /// @param pz @f$pz@f$
```suggestion
      /// @action_function{scalar transformer} boost the 4-momentum @f$p=(p_x,p_y,p_z,E)@f$ along @f$\beta=(\beta_x, \beta_y, \beta_z)@f$
      /// @param px @f$p_x@f$
      /// @param py @f$p_y@f$
      /// @param pz @f$p_z@f$
```

2024-07-31 20:33 UTC, merged